version: '3.8'
services:
  techtadka-store:
    build:
      context: .
    ports:
      - "8080:80"
    
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      retries: 3
