server {
    listen 80;
    server_name techtadkawithishubham.com www.techtadkawithshubham.com;
}

server {
    listen 443 ssl;
    server_name techtadkawithshubham.com www.techtadkawithshubham.com;

    # SSL Certificates — Let's Encrypt
    ssl_certificate     /etc/letsencrypt/live/techtadkawithshubham.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/techtadkawithshubham.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|jpg|ico|woff)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
}
